#!/bin/bash

if [ -f $3 ]; then
  echo "output file exists, please remove it."
  exit
fi

java -Xmx100G -cp CEExperiments.jar Graphflow.LargeBenchmarkQueryDecomposer $2
java -Xmx100G -cp CEExperiments.jar Graphflow.Catalogue $1 catalogue.txt
java -Xmx100G -cp CEExperiments.jar IMDB.AcyclicQueryEvaluation cat catalogue.txt false 3 all false $2
cat estimation.csv >> $3
rm catalogue.txt