#!/bin/bash
  
if [ "$#" -ne 1 ]; then
    cat q.txt
    java -Xmx100G -cp CEExperiments.jar Graphflow.CyclicQueryEvaluation ${2} catalogue.txt true q.txt ${1} true > /dev/null
else
    cat q.txt
    java -Xmx100G -cp CEExperiments.jar IMDB.AcyclicQueryEvaluation cat catalogue.txt false 3 all ${1} q.txt > /dev/null
fi
